EntityFrameWorkPractice/Controllers/EmployeeController.cs
using EntityFrameWorkPractice.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntityFrameWorkPractice.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult GetEmployee()
        {
            var employees = new List<Employee>()
            {
                new Employee(){  EmployeeID =1065,EmployeeName = "Mark Antony",Salary=15000,DateOfJoining=new DateTime(2022,02,12) },
                new Employee(){  EmployeeID =1066,EmployeeName = "Henry Richard",Salary=10000,DateOfJoining=new DateTime(2022,01,01) },
                new Employee(){  EmployeeID =1067,EmployeeName = "Robert",Salary=18000,DateOfJoining=new DateTime(2021,12,24) },
                new Employee(){  EmployeeID =1068,EmployeeName = "Stephen",Salary=26000,DateOfJoining=new DateTime(2021,07,19) },
                new Employee(){  EmployeeID =1069,EmployeeName = "Princy",Salary=13000,DateOfJoining=new DateTime(2022,02,13) }
            };
            return View(employees);
        }
    }
}

EntityFrameWorkPractice/Controllers/ProductController.cs
using EntityFrameWorkPractice.Config;
using EntityFrameWorkPractice.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntityFrameWorkPractice.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Create()
        {
            return View(new Product { Id=0});
        }
        [HttpPost]
        public ActionResult Create(Product product)
        {
            //string insertSql = "INSERT INTO Products(Name,Price,Supplier) VALUES('" + product.Name + "','" + product.Price + "','" + product.Supplier + "')";
            //string updateSql = "UPDATE Products SET Name='" + product.Name + "',Price='" + product.Price + "',Supplier='" + product.Supplier + "' where Id='"+product.Id+"'";
            if(ModelState.IsValid)
            {
                using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
                {
                    using (SqlCommand cmd = new SqlCommand("Product_SaveOrUpdate", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@Id", product.Id);
                        cmd.Parameters.AddWithValue("@Name", product.Name);
                        cmd.Parameters.AddWithValue("@Price", product.Price);
                        cmd.Parameters.AddWithValue("@Supplier", product.Supplier);
                        if (con.State != System.Data.ConnectionState.Open)
                            con.Open();

                        cmd.ExecuteNonQuery();
                    }
                }
                return RedirectToAction("GetAll");
            }
            else
            {
                return View("Create",product);
            }
            
        }
        public ActionResult Search(string search)
        {
            List<Product> products = GetProducts("Products_SearchProduct",search);
            return View("GetAll",products);
        }
        public List<Product> GetProducts(string stored_procedure,string search)
        {
            List<Product> products = new List<Product>();
            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand command = new SqlCommand(stored_procedure, con))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    if (search != null)
                        command.Parameters.AddWithValue("@Filter", search);
                    if (con.State != System.Data.ConnectionState.Open)
                        con.Open();
                    SqlDataReader sqlDataReader = command.ExecuteReader();
                    DataTable datatable = new DataTable();
                    datatable.Load(sqlDataReader);
                    foreach (DataRow dataRow in datatable.Rows)
                    {
                        products.Add(
                            new Product
                            {
                                Id = Convert.ToInt32(dataRow["ID"]),
                                Name = dataRow["Name"].ToString(),
                                Price = Convert.ToDecimal(dataRow["Price"]),
                                Supplier = dataRow["Supplier"].ToString()
                            });
                    }
                }
            }
            return products;
        }
        public ActionResult GetAll()
        {
            List<Product> products = GetProducts("Products_GetAllProduct", null);
           
            return View(products);
        }
        public ActionResult Delete(int id)
        {
            if(id<0)
                return HttpNotFound();
            using(SqlConnection con=new SqlConnection(StoreConnection.GetConnection()))
            {
                using(SqlCommand command=new SqlCommand("Product_DeleteById", con))
                {
                    command.CommandType=CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@Id", id);
                    if(con.State != System.Data.ConnectionState.Open)   
                        con.Open();
                    command.ExecuteNonQuery();
                }
            }
            return  RedirectToAction("GetAll");
        }
        public ActionResult Edit(int id)
        {
            if (id < 0)
                return HttpNotFound();
            var _product = new Product();
            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand command = new SqlCommand("Product_GetById", con))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@Id", id);
                    if (con.State != System.Data.ConnectionState.Open)
                        con.Open();
                    SqlDataReader reader = command.ExecuteReader();
                    DataTable table = new DataTable();
                    if(reader.HasRows)
                    {
                        table.Load(reader);
                        DataRow row = table.Rows[0];
                        _product.Id=Convert.ToInt32(row["ID"]);
                        _product.Name=row["Name"].ToString();
                        _product.Price = Convert.ToDecimal(row["Price"]);
                        _product.Supplier = row["Supplier"].ToString();
                        return View("Create", _product);
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
            }
            
        }
      
    }
}

EntityFrameWorkPractice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!---<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ASP.NET_Sample", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Student List", "GetStudent", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Employee List", "GetEmployee", "Employee", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Student List with Subjects", "GetStudentViewModel", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Product Details", "GetAll", "Product", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
    </html>